export const HTML_GATEWAY_ATTRIBUTE = 'puzzle-gateway';
export const HTML_FRAGMENT_NAME_ATTRIBUTE = 'puzzle-fragment';
export const DEFAULT_POLLING_INTERVAL = 1250;
export const FRAGMENT_STATICS_PATH_NAME = '__static';
export const CONTENT_NOT_FOUND_ERROR = `<script>console.log('Fragment Part does not exists')</script>`;
export const DEFAULT_CONTENT_TIMEOUT = 15000;
export const RENDER_MODE_QUERY_NAME = '__renderMode';
export const PREVIEW_PARTIAL_QUERY_NAME = '__renderMode';
export const API_ROUTE_PREFIX = 'api';
